apiVersion: v1
kind: Pod
metadata:
 name: podman
 labels:
   app.kubernetes.io/name: podman
   app.kubernetes.io/component: database
   app.kubernetes.io/part-of: petclinic
spec:
 containers:
   - name: container
     image: quay.io/devplayground/developer-container-utilities:latest
     args:
       - sleep
       - "infinity"
     securityContext:
       privileged: true
