apiVersion: v1
kind: Deployment
metadata:
  name: db
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: petclinic
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: mysql
      app.kubernetes.io/component: database
      app.kubernetes.io/part-of: petclinic
    replicas: 1
    template:
      metadata:
        labels:
          app.kubernetes.io/name: mysql
          app.kubernetes.io/component: database
          app.kubernetes.io/part-of: petclinic
      spec:
        containers:
        - name: mysql
          image: quay.io/devplayground/developer-container-utilities:latest
          args:
          - sleep
          - "infinity"
          securityContext:
            privileged: true
             
