apiVersion: v1
kind: Pod
metadata:
  labels:
    app.kubernetes.io/name: podman
spec:
 containers:
   - name: container
     image: quay.io/devplayground/developer-container-utilities:latest
     args:
       - sleep
       - "infinity"
     securityContext:
       privileged: true
