apiVersion: v1
kind: Pod
metadata:
  name: podmon
  labels:
    app.kubernetes.io/name: podman
spec:
 containers:
   - name: container
     image: quay.io/podman/stable:latest
     args:
       - sleep
       - "infinity"
     securityContext:
       privileged: true
