apiVersion: v1
kind: Pod
metadata:
 name: podman
spec:
 containers:
   - name: terminal
     image: amoldeshpande/podman-che
     args:
       - sleep
       - "infinity"
     securityContext:
       privileged: true
     
