apiVersion: v1
kind: Pod
metadata:
 name: podman
spec:
 containers:
   - name: container
     image: amoldeshpande/podman-terminal
     args:
       - sleep
       - "infinity"
     securityContext:
       privileged: true
