apiVersion: v1
kind: Pod
metadata:
 name: podman
spec:
 containers:
   - image: amoldeshpande/custom-podman-root
     args:
       - sleep
       - "infinity"
     securityContext:
       privileged: true
