apiVersion: v1
kind: Pod
metadata:
 name: podman-priv
spec:
 containers:
   - name: priv
     image: amoldeshpande/custom-podman-root
     args:
       - sleep
       - "infinity"
     command: ["podman pull amoldeshpande/sampleapp1-v1:latest"]
     securityContext:
       privileged: true
     
