swagger: '2.0'
info:
  title: Loan Provider API
  version: 1.0.0
  x-ibm-name: loan-provider-api
host: $(catalog.host)
schemes:
  - https
basePath: /
produces:
  - application/json
paths:
  /validateLoan:
    get:
      summary: Loan Approval Api
      parameters:
        - name: name
          in: query
          description: name string
          required: true
          type: string
        - name: salary
          in: query
          description: salary string
          required: true
          type: string
        - name: loan
          in: query
          description: loan string
          required: true
          type: string
        - name: creditscore
          in: query
          description: creditscore string
          required: true
          type: string
      responses:
        '200':
          description: Success
  
x-ibm-configuration:
  enforced: true
  testable: true
  phase: realized
  cors:
    enabled: true
  assembly:
    execute:
      - operation-switch:
          title: operation-switch
          case:
            - operations:
                - verb: get
                  path: /validateLoan
              execute:
                - invoke:
                    title: invoke-add
                    timeout: 60
                    verb: GET
                    cache-response: protocol
                    cache-ttl: 900
                    stop-on-error:
                      - null
                    version: 1.0.0
                    target-url: 'https://sample-loan-app.eu-gb.mybluemix.net/validateLoan?name={name}&salary={salary}&loan={loan}&creditscore={creditscore}'
              - operations:
                - verb: get
                  path: /validateLoan2
              execute:
                - invoke:
                    title: invoke-add
                    timeout: 60
                    verb: GET
                    cache-response: protocol
                    cache-ttl: 900
                    stop-on-error:
                      - null
                    version: 1.0.0
                    target-url: 'https://sample-loan-app.eu-gb.mybluemix.net/validateLoan2?name={name}&salary={salary}&loan={loan}&creditscore={creditscore}'
          otherwise: []
          version: 1.0.0
    catch: []
consumes:
  - application/json
