swagger: '2.0'
info:
  title: Loan Provider API
  version: 1.0.0
  x-ibm-name: loan-provider-api
host: $(catalog.host)
schemes:
  - https
basePath: /
produces:
  - application/json
paths:
  /validateLoan:
    get:
      summary: Loan Approval Api
      parameters:
        - name: email
          in: query
          description: email string
          required: false
          type: string
        - name: fname
          in: query
          description: fname string
          required: false
          type: string
        - name: lname
          in: query
          description: lname string
          required: false
          type: string
        - name: loan
          in: query
          description: loan string
          required: true
          type: string
        - name: sourceIncome
          in: query
          description: sourceIncome string
          required: false
          type: string
        - name: income
          in: query
          description: income string
          required: true
          type: string
        - name: reason
          in: query
          description: reason string
          required: false
          type: string
      responses:
        '200':
          description: Success
  
x-ibm-configuration:
  enforced: true
  testable: true
  phase: realized
  cors:
    enabled: true
  assembly:
    execute:
      - operation-switch:
          title: operation-switch
          case:
            - operations:
                - verb: get
                  path: /validateLoan
              execute:
                - invoke:
                    title: invoke-add
                    timeout: 60
                    verb: GET
                    cache-response: protocol
                    cache-ttl: 900
                    stop-on-error:
                      - null
                    version: 1.0.0
                    target-url: 'http://{HOST}/validateLoan?email={email}&fname={fname}&lname={lname}&loan={loan}&sourceIncome={sourceIncome}&income={income}&reason={reason}'
          otherwise: []
          version: 1.0.0
    catch: []
consumes:
  - application/json
